PersonalProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makethedifference.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

makethedifference/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django_resized import ResizedImageField
import uuid


class Tag(models.Model):
    caption = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.caption}'


class User(AbstractUser):
    name = models.CharField(
        max_length=100,
        null=True,
    )
    email = models.EmailField(
        unique=True,
        null=True,
    )

    bio = models.TextField()

    creator_of_event = models.BooleanField(default=True, null=True)

    avatar = ResizedImageField(size=[250, 250], default='avatar.jpg')

    website = models.URLField(max_length=500, null=True, blank=True)

    created = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    # id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Cause(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=800, null=True, blank=True)

    image = ResizedImageField(size=[250, 250], default='thelogo.PNG')

    location = models.URLField()  # Location from Google Maps
    followers = models.ManyToManyField(
        User,
        blank=True,
        related_name='causes',
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    likes = models.ManyToManyField(User, related_name='cause_likes')
    tags = models.ManyToManyField(Tag, related_name='cause_tags')

    def total_cause_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title


class Event(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField(null=True, blank=True, )
    cause = models.ForeignKey(Cause, on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='event_creator')
    image = ResizedImageField(size=[500, 500], default='thelogo.PNG')
    location = models.URLField()
    participants = models.ManyToManyField(
        User,
        blank=True,
        related_name='events',
    )
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    created = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )
    likes = models.ManyToManyField(User, related_name='event_likes')
    tag = models.ManyToManyField(Tag, related_name='event_tags')

    #
    # id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def total_event_likes(self):
        return self.likes.count()

    def __str__(self):
        try:
            return str(self.cause) + ' --- ' + str(self.creator.username) + ' --- ' + str(self.title)
        except AttributeError:
            return str(self.cause) + ' --- ' + str(self.title)


class Comment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='event_comments')
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True)
    text = models.TextField(max_length=400)
    created_on = models.DateTimeField(default=timezone.now, null=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.text, self.name)

    @property
    def number_of_comments(self):
        return Comment.objects.filter(event=self).count()

templates/account_password.html
{% extends 'main.html' %}
{% load django_bootstrap5 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

{% block content %}

<style>
.field-icon {
  float: right;
  margin-left: -25px;
  margin-top: -25px;
  position: relative;
  z-index: 2;
}
</style>
<h4 align="center">
Change Your Password
</h4>
<div align="center" class="container">
        <div class="row my-5">
            <div class="col-md-12">
    <form method="post" class="form">
    {% csrf_token %}
        <div>
    <label>Current Password </label>
            <label for="password-field"></label><input type="password" name="oldpassword" id="id_password1"/>
            <input type="checkbox"
           onclick="Toggle()">
    <strong>Show Password</strong>

    <script>
        // Change the type of input to password or text
        function Toggle() {
            var temp = document.getElementById("id_password1");
            if (temp.type === "password") {
                temp.type = "text";
            }
            else {
                temp.type = "password";
            }
        }
    </script>
                </div>

    </div>
<br>
    <div>
    <label style="margin-left: 25px"> New Password</label>
        <label>
            <input type="password" name="password1" id="id_password"/>
            <input type="checkbox"
           onclick="Toggle()">
    <strong>Show Password</strong>

    <script>
        // Change the type of input to password or text
        function Toggle() {
            var temp = document.getElementById("id_password");
            if (temp.type === "password") {
                temp.type = "text";
            }
            else {
                temp.type = "password";
            }
        }
    </script>
        </label>
    </div>
<br>
      <div>
    <label>Re-enter Password</label>
        <label>
            <input type="password" name="password2" id="id_password"/>
            <input type="checkbox"
           onclick="Toggle()">
    <strong>Show Password</strong>

    <script>
        // Change the type of input to password or text
        function Toggle() {
            var temp = document.getElementById("id_password");
            if (temp.type === "password") {
                temp.type = "text";
            }
            else {
                temp.type = "password";
            }
        }
    </script>

        </label>
    </div>
<br>
      <div>
        <label>
            <input type="submit" class="btn btn-primary" value="Change Password"/>
        </label>
    </div>

    </form>


{% endblock content %}

templates/cause.html
{% extends 'main.html' %}
{% load social_share %}


{% block content %}

<div align="center" class="card-deck">
  <div align="center" class="card; rounded" style="background-image: url('https://i.ibb.co/jJgnKZW/plant-card-2.jpg');background-size: cover; width: 800px; margin-left: 30px; margin-right: 20px; border-color: darkslateblue">
<div class="card-body">
    <h4 align="center" style="padding: 10px; color: navajowhite">
{{ cause.title }}
</h4>
         {% for tag in cause_tags %}
                <button class=" btn btn-group-sm" style="background-color: darkslategrey; color: floralwhite; padding: 0.5px; margin: 5px ">{{ tag.caption }}</button>
            {% endfor %}
<p class="lead" style="color: floralwhite; margin: 10px">{{ cause.description }}</p>
        <button class="btn btn-sm" style="background-color: darkslategrey; padding-left: 15px; padding-right: 15px; margin: 5px "><a style="color: floralwhite; text-decoration: none" href="{{ cause.location }}" target="_blank">Location &#127758;</a></button>
        {% if user.is_authenticated %}
          {% if following %}
              <p style="color: floralwhite">You are already following this cause. </p>
        {% else %}
       <button class="btn btn-sm" style="background-color: darkslategrey; padding-left: 15px; padding-right: 15px; margin: 5px"> <a style="color: floralwhite; text-decoration: none; font-size: large" href="{% url 'follow-cause-conf' cause.id %}">Follow</a></button>
        {% endif %}
        {% else %}
        <p style="color: floralwhite">To Follow this Cause, please <a style="text-decoration: none;" href="{% url 'login-page' %}"> Login </a> </p>
        {% endif %}

    <br><br/>

<form action="{% url 'like-cause' cause.id %}" method="POST">
    {% csrf_token %}
{% if user.is_authenticated %}
    {% if liked %}
    <button class="btn btn-sm" style="background-color: darkslategrey; color: floralwhite; padding-left: 15px; padding-right: 15px; margin: 5px" type="submit" name="cause_like_id" value="{{ cause.id }}">
        Unlike &#128148; </button>
    {% else %}
    <button class="btn btn-sm" style="background-color: darkslategrey; color: floralwhite; padding-left: 15px; padding-right: 15px; margin: 5px" type="submit" name="cause_like_id" value="{{ cause.id }}">
        Like &#x1F49C; </button>
    {% endif %}
{% else %}
<small style="color:antiquewhite;">You need to be logged in to like this cause.</small>
{% endif %}

{% if cause.total_cause_likes %}
    <h8 style="color: floralwhite"> {{ total_likes }} likes </h8>
{% else %}
<p>Be the first to like this cause.</p>
{% endif %}
    </form>
<button class="btn btn-sm" style="background-color: darkslategrey; padding-left: 15px; padding-right: 15px; margin: 5px"> <a style="color: floralwhite; text-decoration: none; font-size: large" href="{% post_to_facebook object_or_url %}"></a></button>
 </div>
  </div>
<br>
     <section>
    <h3 align="center" style="color: darkslategrey; margin-bottom: 20px">Events related to this Cause</h3>
     <div class="d-flex flex-row bd-highlight mb-3">
     {% if not cause.event_set.all %}
     <p style="color: darkslategrey; margin-left: 550px">You will be the first one to create an event related to this cause!</p>
     {% else %}
        {% for event in cause.event_set.all %}
            <div class="flex-shrink-0 card" style="background-image: url('https://i.ibb.co/jJgnKZW/plant-card-2.jpg'); background-size: cover; width: 200px; margin-left: 30px; margin-right: 15px; border-color: darkslateblue" >

            <a style="padding: 20px; color: floralwhite; text-decoration: none; font-size: larger" href="{% url 'event-details' event.id %}">{{ event.title }}</a>

            </div>
        {% endfor %}
     {% endif %}
    </div>
    <div>

    <div align="center">
        {% if user.is_authenticated and user in cause.followers.all %}
    <a class="btn btn-sm" style="background-color: darkolivegreen; color: floralwhite; padding-right: 40px; padding-left: 40px; margin: 15px; font-size: large" href="{% url 'create-event' cause.id %}">Create Event</a>
        {% else %}
        <p style="font-size: large">To Create an Event, please <a href="{% url 'login-page' %}"> Login </a> and Follow the Cause. </p>
    {% endif %}
 </div>

{#    <img class="card-img-top" src="{{ cause.image.url }}" alt="cause_image">#}

    <br>
        <section>
 <div>
 <h3 align="center" style="color: darkslategrey">{{ cause.followers.count }} Cause Followers</h3>
 <div class="d-flex flex-row bd-highlight mb-3">
        {% for user in cause.followers.all %}
            <div class="flex-shrink-0 card" style="background-image: url('https://i.ibb.co/jJgnKZW/plant-card-2.jpg');background-size: cover; width: 200px; margin-left: 30px; margin-right: 15px; border-color: darkslategrey" >
            <a href="{% url 'user-profile-page' user.id%}">
                <div>
                    <div>
                        <img src="{{user.avatar.url}}" class="rounded-circle" alt="user_avatar" width="100%" height="90vh" style= "object-fit: scale-down; padding-top: 10px"/>
                        <a style="text-decoration: none; color: floralwhite; padding-left: 50px" href="{% url 'user-profile-page' user.id %}">{{ user.name }}</a>
                    </div>
                </div>
            </a>
            </div>
        {% endfor %}

    </div>
        </section>



{% endblock content %}

templates/create_event_form.html
{% extends 'main.html' %}
{% load django_bootstrap5 %}

{% block content %}

<h4 align="center"> Create event for {{ cause.title }} </h4>
     <div class="container">
        <div class="row my-5">
            <div class="col-md-12">
    <form method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
{#        {{ form.as_p }}#}
        <input type="submit" class="btn btn-primary" value="Update Event"/>
    </form>
</div>
        </div>
    </div>

{% endblock content %}

templates/edit_account.html
{% extends 'main.html' %}
{% load django_bootstrap5 %}

{% block content %}

<h3 align="center">
Edit Your Account
</h3>
 <div class="container">
        <div class="row my-5">
            <div class="col-md-12">
<form method="POST" enctype="multipart/form-data" class="form">
    {% csrf_token %}
     {% bootstrap_form form %}
{#    {% for field in form %}#}
{#        <div>#}
{#            <label>#}
{#                {{ field.label }}#}
{#            </label>#}
{#        {{ field }}#}
{#        </div>#}
{#    {% endfor %}#}
<div>
    <input type="submit" class="btn btn-primary" value="Update Account" />
</div>
</form>
</div>

{% endblock content %}

templates/event_details.html
{% extends 'main.html' %}
{% load social_share %}
{% block content %}

<div align="center" class="card-deck">
  <div align="center" class="card; rounded" style="background-image: url('https://i.ibb.co/jJgnKZW/plant-card-2.jpg');background-size: cover; width: 650px; margin-left: 30px; margin-right: 20px; border-color: darkslateblue">
<div class="card-body">
    <h3 align="center" style="color: navajowhite; padding: 10px">
{#    <img src="{{ event.image.url }}" alt="event_image" width="150">#}
        {{ event.title }}
    </h3>
{% for tag in event_tags %}
    <button class=" btn btn-group-sm" style="background-color: darkslategrey; color: navajowhite; padding: 0.5px; margin: 5px ">{{ tag.caption }}</button>
            {% endfor %}
    <p class="lead" style="color: floralwhite; margin: 10px">{{ event.description }}</p>
    {% if not creator %}
        <div style="margin-bottom: 20px"><p style="color: floralwhite; margin: 10px">Created by:</p><a style="color: navajowhite; text-decoration: none" href="{% url 'user-profile-page' user.id %}">{{ event.creator.name }}</a></div>

{% else %}
        <p>.</p>
{% endif %}
    <button class="btn btn-sm" style="background-color: darkslategrey; padding-left: 15px; padding-right: 15px; margin: 5px "><a  style="color: floralwhite; text-decoration: none" href="{{ event.location }}" target="_blank">Location &#127758;</a></button>
{% if user.is_authenticated %}
{% if registered %}
        <p style="color: floralwhite; margin: 10px">You are already registered for this event. </p>
        {% else %}
    <button class=" btn btn-group-sm" style="background-color: darkslategrey; color: navajowhite; padding: 3px; margin: 5px "><a style="color: floralwhite; text-decoration: none; margin: 10px" href="{% url 'register-event-conf' event.id %}">Register for this event</a></button>
        {% endif %}
{% else %}
<p style="color: navajowhite; margin: 10px">To Register for this Event, please <a href="{% url 'login-page' %}"> Login </a> </p>
{% endif %}

<br>

        <form action="{% url 'like-event' event.id %}" method="POST">
    {% csrf_token %}
            {% if user.is_authenticated %}
    {% if liked %}
     <button class="btn btn-sm" style="background-color: darkslategrey; color: floralwhite; padding-left: 15px; padding-right: 15px; margin: 5px" type="submit" name="event_like_id" value="{{ event.id }}">
        Unlike &#128148; </button>
    {% else %}
    <button class="btn btn-sm" style="background-color: darkslategrey; color: floralwhite; padding-left: 15px; padding-right: 15px; margin: 5px" type="submit" name="event_like_id" value="{{ event.id }}">
        Like &#x1F49C; </button>
    {% endif %}
{% else %}
<small style="color:floralwhite;">You need to be logged in to like this event.</small>
{% endif %}
    <h8 style="color: floralwhite"> {{ total_event_likes }} likes </h8>
    </form>
<button class="btn btn-sm" style="background-color: darkslategrey; padding-left: 15px; padding-right: 15px; margin: 5px"> <a style="color: floralwhite; text-decoration: none; font-size: large" href="{% post_to_facebook object_or_url %}"></a></button>
 </div>
  </div>
<br>

 <div>
 <h3 align="center" style="color: darkslategrey">{{ event.participants.count }} Event Participants</h3>
 <div class="d-flex flex-row bd-highlight mb-3">
        {% for user in event.participants.all %}
            <div class="flex-shrink-0 card" style="background-image: url('https://i.ibb.co/jJgnKZW/plant-card-2.jpg');background-size: cover; width: 200px; margin-left: 30px; margin-right: 15px; border-color: darkslategrey" >
            <a href="{% url 'user-profile-page' user.id%}">
                <div>
                    <div>
                        <img src="{{user.avatar.url}}" class="rounded-circle" alt="user_avatar" width="100%" height="90vh" style= "object-fit: scale-down; padding-top: 10px"/>
                        <a style="text-decoration: none; color: floralwhite; padding-left: 50px" href="{% url 'user-profile-page' user.id %}">{{ user.name }}</a>
                    </div>
                </div>
            </a>
            </div>
        {% endfor %}

    </div>
 <br><br/>
                    <h6 align="center" style="text-decoration: underline">Recent comments...</h6>

            {% for comment in event.event_comments.all %}
                <div align="center" style="font-family: Courier,fantasy">
                    <h8>{{ comment.name }}</h8>: <h9>{{ comment.text }}</h9>
                <br>
                <h9>{{ comment.created_on }}</h9>
            {% endfor %}
                </div>
<br>
 <div>
     <button class="btn btn" style="margin-left:50px; background-color: darkslategrey"><a style="color: antiquewhite; text-decoration: none" href="{% url 'post-comment' event.id %}">Add Your Comment</a></button></div>


<hr style="margin: 25px">

    <div align="center"> Want to ask a question about this event?
        You can <a href="mailto:{{ event.creator.email }};
                            makethedifference.varna@gmail.com">email us directly.</a></div>

{% endblock content %}

templates/follow_cause_confirmation.html
{% extends 'main.html' %}

{% block content %}

{#    <form method="POST">#}
{#{% csrf_token %}#}
{#<button class="btn-sm btn-outline-primary" style="margin-left: 25px"> <a style="text-decoration: none" href="{% url 'cause' cause.id %}">Go back</a></button>#}
{#<input class="rounded" style="background-color: darkolivegreen; color: antiquewhite; padding: 3px;" type="submit" value="Confirm"/>#}
{#</form>#}

        <form method="POST">
{% csrf_token %}
            <button class="btn-sm btn-outline-primary" style="margin-left: 25px"> <a style="text-decoration: none" href="{% url 'cause' cause.id %}">Go back</a></button>
    {% if following %}
        <input class="rounded" style="background-color: darkolivegreen; color: antiquewhite; padding: 3px;" type="submit" value="Unfollow"/>
        {% else %}
        <input class="rounded" style="background-color: darkolivegreen; color: antiquewhite; padding: 3px;" type="submit" value="Confirm"/>
        {% endif %}
        </form>
{% endblock content %}

templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap 5 Footer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  </head>
  <body>
{#    <div#}
{#  class="bg-image d-flex justify-content-center align-items-center rounded"#}
{#  style="#}
{#    background-image: url('https://i.ibb.co/FgR1zmW/output-onlinepngtools-5.png');#}
{#    height: 30vh; margin-top: 100px; margin-left: 25px; margin-right: 25px;#}
{#  "#}
{#>#}
{#    <img src="{% static 'images/logo-opaque.png' %}" class="rounded-circle" align="right" alt="logo" width="300" height="200">#}
{##}
{#</div>#}
    <footer class="container p-4 rounded pt-5" style="margin-top: 50px">
      <div class="d-lg-flex justify-content-between">
        <div>
{#          <span>Email us </span>#}
             <div id="google_element"></div>
    <script src="https://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"></script>
    <script>
    function loadGoogleTranslate() {
        new google.translate.TranslateElement("google_element");
    }
    </script>

        </div>


        <div class="copyright">
          <p>developed and maintained by <a href="{% url 'about' %}" target="_blank">Nora Pavlova</a></p>

        </div>
        <div>
          <ul class="d-flex gap-3 list-unstyled">
            <li><a href="https://www.facebook.com/nori.gore/"><i class="bi bi-facebook"></i></a></li>
            <li><a href="https://www.instagram.com/cinnnammonn/"><i class="bi bi-instagram"></i></a></li>
          </ul>
        </div>
      </div>
    </footer>

  </body>

</html>

templates/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}


    <section style="margin-top: 20px">
    <h1 align="center" style="margin-bottom: 20px"> New Events</h1>
        <div class="d-flex flex-row bd-highlight mb-3; container-fluid; justify-content-center" >
        {% for event in events %}
            <div class="flex-shrink-0 card" style=" background-image: url('https://i.ibb.co/6JRs7kZ/blue-opaq.png'); background-size: cover; width: 250px; margin-left: 30px; margin-right: 20px; border-width: 20px" >
            <img src="{{ event.image.url }}" class="rounded-circle" alt="event_image" width="100%" height="90vh" style= "object-fit: scale-down; padding-top: 10px">

            <a style="text-decoration: none" href="{% url 'event-details' event.id %}">

            <h5 class="card-title" style="color: navajowhite; margin-top: 5px; margin-bottom: 15px; padding: 5px" align="center"> {{ event.title }}</h5>
                <p class="card-text" style="color: navajowhite; padding-left: 10px">{{ event.participants.all.count }} registered</p>
                <p class="card-text" style="color: navajowhite; padding-left: 10px; padding-bottom: 10px">Start Date: {{ event.start_date|date }}</p>
{#                <p class="card-text" style="padding-left: 10px; padding-bottom: 10px">End Date: {{ event.end_date }}</p>#}
            </a>
{#            <p class="card-text" style="padding-left: 10px;"> <a href="{{ event.location }}" target="_blank">Location</a></p>#}
            </div>
        {% endfor %}
    </div>
    </section>

{#    <hr style="margin:25px">#}
    <div
  class="bg-image d-flex justify-content-center align-items-center rounded"
  style="
    background-image: url('https://i.ibb.co/FgR1zmW/output-onlinepngtools-5.png');
    height: 30vh; margin-top: 50px; margin-left: 25px; margin-right: 25px;
  "
>
    <img src="{% static 'images/logo-opaque.png' %}" class="rounded-circle" align="right" alt="logo" width="300" height="200">

</div>
    <br><br>

        <section>
    <h1 style="margin-bottom: 20px" align="center">New Causes</h1>

    <div class="d-flex flex-row bd-highlight mb-3; container-fluid; justify-content-center">
        {% for cause in causes %}
            <div class="flex-shrink-0 card" style= "background-image: url('https://i.ibb.co/GsnRQw4/green-opaq.png'); background-size: cover; width: 250px; margin-left: 30px; margin-right: 20px; border-width: 20px" >
            <img src="{{ cause.image.url }}" class="rounded-circle" alt="cause_image" width="100%" height="90vh" style= "object-fit: scale-down; padding-top: 10px">
            <a style="text-decoration: none; color: black" href="{% url 'cause' cause.id %}">
            <h5 class="card-title" style="margin-top: 5px; margin-bottom: 15px; padding: 5px; color: navajowhite" align="center">{{ cause.title }}</h5>
                <p class="card-text" style="padding-left: 10px; margin-bottom: 5px; color: navajowhite">{{ cause.followers.all.count }} following</p>
                <p> <a style="text-decoration: none; color: navajowhite; padding-left: 10px" href="{{ cause.location }}" target="_blank">Location</a></p>

            </a>
             </div>
        {% endfor %}
    </div>
    </section>

        <div
  class="bg-image d-flex justify-content-center align-items-center rounded"
  style="
    background-image: url('https://i.ibb.co/FgR1zmW/output-onlinepngtools-5.png');
    height: 30vh; margin-top: 100px; margin-left: 25px; margin-right: 25px;
  "
>
    <img src="{% static 'images/logo-opaque.png' %}" class="rounded-circle" align="right" alt="logo" width="300" height="200">

</div>
    <br><br>
{#    <hr style="margin:25px">#}
    <section>
    <h2 align="center">The ChangeMakers</h2>
    <p align="center">{{ users_count }} active changemakers. Join us!</p>
     <div class="d-flex flex-row bd-highlight mb-3; container-fluid; justify-content-center">
        {% for user in users %}
            <div class="flex-shrink-0 card" style=" background-image: url('https://i.ibb.co/NYJfPfx/plant-opaq.png');background-size: cover; width: 200px; margin-left: 30px; margin-right: 15px; border-width: 8px" >
             <img src="{{ user.avatar.url }}" class="rounded-circle" alt="user_avatar" width="100%" height="90vh" style= "object-fit: scale-down; padding-top: 10px">
            <a style="color: navajowhite; text-decoration: none; padding-left: 50px" href="{% url 'user-profile-page' user.id %}">{{ user.name }}</a>

            </div>
        {% endfor %}
    </div>
    <div>
        {% for page in pages %}
            <a href="?page{{ page }}">{{ page }}</a>
        {% endfor %}
    </div>
    </section>

{% endblock %}

templates/post_comment.html
{% extends 'main.html' %}
{% load django_bootstrap5 %}

{% block content %}
    {% if user.is_authenticated %}
<section >
    <h4 style="margin-left: 25px">Your Comment</h4>
  <form style="margin-left: 25px; margin-right: 25px" method="POST">
    {% csrf_token %}
    <div>
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary" style="margin-left: 25px">Add comment</button>
    </div>
  </form>
</section>
    {% else %}
    <p style="margin-left: 25px">To post a comment, please <a href="{% url 'login-page' %}"> Login </a></p>
{% endif %}
{% endblock %}

templates/register_event_confirmation.html
{% extends 'main.html' %}

{% block content %}

    <form method="POST">
{% csrf_token %}
        <button class="btn-sm btn-outline-primary" style="margin-left: 25px"> <a style="text-decoration: none" href="{% url 'event-details' event.id %}">Go back</a></button>
<input class="rounded" style="background-color: darkolivegreen; color: antiquewhite; padding: 3px;"type="submit" value="Confirm"/>
</form>
{% endblock content %}

templates/scroll_top.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
}

#myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: darkslategrey;
  color: antiquewhite;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}
</style>
    <title></title>
</head>
<body>

<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

<script>
// Get the button
let mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

</body>
</html>